# Generated by Django 2.1.5 on 2019-04-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='name',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
